/**
 * @file generated_params.h
 * @brief Auto-generated Yaskawa GA700 Parameter Database & Lookup
 * Generated by generate_code.py. Total parameters: 1003
 */

#ifndef GENERATED_PARAMS_H
#define GENERATED_PARAMS_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#define GA700_PARAM_COUNT 1003

typedef struct {
    const char *code;        // e.g. "A1-00"
    const char *name;        // e.g. "Language Selection"
    uint16_t address;        // e.g. 0x0100
    uint16_t page;           // e.g. 8
    const char *section_id;  // e.g. "10.4"
    const char *group_id;    // e.g. "A1"
} ga700_param_meta_t;

extern const ga700_param_meta_t g_ga700_params[GA700_PARAM_COUNT];

/**
 * @brief Find parameter metadata by 16-bit register address (Binary search O(log N))
 */
const ga700_param_meta_t* ga700_find_param_by_addr(uint16_t addr);

/**
 * @brief Find parameter metadata by code (e.g. "b1-01")
 */
const ga700_param_meta_t* ga700_find_param_by_code(const char *code);

/**
 * @brief Check if a register address exists in GA700 parameter database
 */
bool ga700_is_valid_param_addr(uint16_t addr);

#ifdef __cplusplus
}
#endif

#endif // GENERATED_PARAMS_H
